function data = import_lowell_MA(filename, dataLines)
%IMPORTFILE Import data from a text file
%  SEA3152120MA = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  SEA3152120MA = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  SEA3152120MA = importfile("C:\Users\bduffy2018\OneDrive - Florida Institute of Technology\School\2021 Spring\OCE2901\Deployment 032121\1404104_SEA_3_15_21_2_(0)_MA.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Mar-2021 11:43:45

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "Ax", "Ay", "Az", "Mx", "My", "Mz"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Time", "TimeZone", "America/New_York", "InputFormat", "uuuu-MM-dd'T'HH:mm:ss.SSS");

% Import the data
data = readtable(filename, opts);

end