function YRP = import_lowell_YRP(filename, order, dataLines)
%IMPORTFILE Import data from a text file
%  SEA3152120YRP = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  SEA3152120YRP = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  SEA3152120YRP = importfile("C:\Users\bduffy2018\OneDrive - Florida Institute of Technology\School\2021 Spring\OCE2901\Deployment 032121\1404104_SEA_3_15_21_2_(0)_YRP.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Mar-2021 12:32:33

%% Input handling

% If dataLines is not specified, define defaults
arguments
    filename
    order = 'YPR'
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
switch order
    case 'RPY'
        opts.VariableNames = ["Time", "Roll", "Pitch", "Yaw"];
    otherwise
        opts.VariableNames = ["Time", "Yaw", "Pitch", "Roll"];
end
opts.VariableTypes = ["datetime", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Time", "InputFormat", "uuuu-MM-dd'T'HH:mm:ss.SSS");

% Import the data
YRP = readtable(filename, opts);
end